
module.exports = {
    USER_NEAR_BY_DISTANCE: 5000, // 5km
    PARTNER_NEAR_BY_DISTANCE: 50000, // 50km
    PASSWORD_SALT_ROUNDS: 10,
    TWENTY_FOUR_HOURS: 86400,
    USER_DEFAULT_NAME: 'Still Anonymous'
}